sudo: required
services:
    - docker
#before_install:
#   - docker build -t maipal/docker-flow -f Dockerfile.dev .
#script:
#   - docker run -e CI=true maipal/docker-flow npm run test
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-flow"
    env: "Dockerflow-env-1"
    bucket_path: "docker"
    bucket_name: "elasticbeanstalk-ap-south-1-991425440433"
    on:
        branch: main
    access_key_id: $ACCESS_KEY_ID
    secret_access_key:
        secure: $SECRET_ACCESS_KEY
