sudo: required
services:
    - docker
before_install:
    - docker build -t maipal/docker-flow -f Dockerfile.dev .
script:
    - docker run -e CI=true maipal/docker-flow npm run test
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker_flow"
    env: "Dockerflow-env-1"
    bucket_name: "elasticbeanstalk-ap-south-1-991425440433"
    bucket_path: "resources/environments/docker_flow"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
